backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: media
collections:
  - name: "class"
    label: "Class"
    folder: "classes"
    create: true
    extension: json
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "json"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Prerequisites", name: "prereqs", widget: "markdown"}
      - label: "Topics"
        name: "topics"
        widget: "list"
        field:
          - {label: "Topic", name: "topic", widget: "string"}
  - name: "notebook"
    label: "Notebook"
    folder: "notebooks"
    create: true
    extension: json
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
